/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_signUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_signIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_verifyEmailToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RoleController_getRoles"];
        put?: never;
        post: operations["RoleController_createRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RoleController_getRoleById"];
        put?: never;
        post?: never;
        delete: operations["RoleController_deleteRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{id}/grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RoleController_addGrants"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{roleId}/grants/{resourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["RoleController_deleteRoleGrant"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ResourceController_findAll"];
        put?: never;
        post: operations["ResourceController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ResourceController_findOne"];
        put?: never;
        post?: never;
        delete: operations["ResourceController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SignUpDto: {
            /** Format: email */
            email: string;
        };
        SignInDto: {
            username: string;
            password: string;
            browserId: string;
        };
        GrantBaseCreateDto: {
            /** Format: uuid */
            roleId: string;
            /** Format: uuid */
            resourceId: string;
            action: string;
            attribute?: string;
        };
        RoleBaseCreateDto: {
            status: Record<string, never>;
            grants?: components["schemas"]["GrantBaseCreateDto"][];
            name: string;
            slug: string;
            description: string;
        };
        CreateResourceDto: {
            name: string;
            slug: string;
            description?: string;
        };
        UserDeleteDto: {
            /** Format: uuid */
            userId: string;
        };
        UserBulkDeleteDto: {
            userIds: string[];
        };
        UserQueryDto: {
            page?: number;
            limit?: number;
            search?: string;
            sortBy?: string;
            /** @enum {string} */
            sortOrder?: "asc" | "desc";
            status?: string;
            sex?: string;
            /** Format: date-time */
            birthdateFrom?: string;
            /** Format: date-time */
            birthdateTo?: string;
            /** Format: date-time */
            createdAtFrom?: string;
            /** Format: date-time */
            createdAtTo?: string;
        };
        UserBaseDto: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            slug: string;
            firstName: string;
            lastName?: string | null;
            /** Format: uuid */
            avatarId?: string;
            status: Record<string, never>;
        };
        UserBaseResponseDto: {
            /** Format: uuid */
            id: string;
            firstName: string;
            lastName?: string | null;
            slug: string;
        };
        UserFullDto: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            slug: string;
            firstName: string;
            lastName?: string | null;
            /** Format: uuid */
            avatarId?: string;
            status: Record<string, never>;
            address?: string;
            /** Format: date-time */
            birthdate?: string;
            msisdn?: string;
            sex?: Record<string, never>;
            createdAt: Record<string, never>;
            updatedAt: Record<string, never>;
        };
        UserFullCreateDto: {
            slug?: string;
            /** Format: email */
            email: string;
            firstName: string;
            lastName?: string | null;
            /** Format: uuid */
            avatarId?: string;
            status: Record<string, never>;
            address?: string;
            /** Format: date-time */
            birthdate?: string;
            msisdn?: string;
            sex?: Record<string, never>;
        };
        UserFullUpdateDto: {
            /** Format: email */
            email?: string;
            firstName?: string;
            lastName?: string | null;
            /** Format: uuid */
            avatarId?: string;
            status?: Record<string, never>;
            address?: string;
            /** Format: date-time */
            birthdate?: string;
            msisdn?: string;
            sex?: Record<string, never>;
            slug?: string;
        };
        UserFullResponseDto: {
            avatar: string | null;
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            slug: string;
            firstName: string;
            lastName?: string | null;
            address?: string;
            /** Format: date-time */
            birthdate?: string;
            msisdn?: string;
        };
        UserAuthDto: {
            password: string;
            salt: string;
            username: string;
            /** Format: uuid */
            roleId: string;
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            status: Record<string, never>;
        };
        UserAuthCreateDto: {
            /** Format: email */
            email: string;
            status: Record<string, never>;
            password: string;
            salt: string;
            username: string;
            /** Format: uuid */
            roleId: string;
        };
        UserAuthUpdateDto: {
            /** Format: email */
            email?: string;
            status?: Record<string, never>;
            password?: string;
            salt?: string;
            username?: string;
            /** Format: uuid */
            roleId?: string;
        };
        RoleBaseDto: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            status: Record<string, never>;
            description: string;
        };
        UserAuthWithRoleDto: {
            password: string;
            salt: string;
            username: string;
            /** Format: uuid */
            roleId: string;
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            status: Record<string, never>;
            role: components["schemas"]["RoleBaseDto"];
        };
        RoleBriefResponseDto: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
        };
        UserPayloadDto: {
            role: components["schemas"]["RoleBriefResponseDto"];
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
        };
        TokenPairDto: {
            accessToken: string;
            refreshToken: string;
        };
        RefreshTokenResponseDto: {
            user: components["schemas"]["UserPayloadDto"];
            tokens: components["schemas"]["TokenPairDto"];
        };
        JwtPermissionDto: {
            role: string;
            resource: string;
            action: string;
            attribute: string;
        };
        JwtPayloadDto: {
            /**
             * Format: uuid
             * @description Id người dùng
             */
            userId: string;
            /**
             * Format: email
             * @description Email người dùng
             */
            email: string;
            /** @description Fingerprint trình duyệt */
            browserId: string;
            /** @description Permissions của người dùng */
            permissions: components["schemas"]["JwtPermissionDto"][];
        };
        QueryImageDto: {
            page?: number;
            limit?: number;
            search?: string;
            sortBy?: string;
            /** @enum {string} */
            sortOrder?: "asc" | "desc";
            name?: string;
            type?: string;
            /** Format: uuid */
            uploaderId?: string;
            /** Format: date-time */
            createdAtFrom?: string;
            /** Format: date-time */
            createdAtTo?: string;
            /** Format: date-time */
            updatedAtFrom?: string;
            /** Format: date-time */
            updatedAtTo?: string;
        };
        BulkDeleteImageDto: {
            imageIds: string[];
        };
        ImageBaseDto: {
            /** Format: uuid */
            id?: string;
            caption?: string;
            description?: string;
            /** Format: uri */
            publicUrl: string;
        };
        ImageFullDto: {
            /** Format: uuid */
            id?: string;
            caption?: string;
            description?: string;
            /** Format: uri */
            publicUrl: string;
            name: string;
            /** Format: uri */
            redirectLink?: string;
            type?: string;
            /** Format: uuid */
            uploaderId: string;
        };
        ImageFullCreateDto: {
            caption?: string;
            description?: string;
            /** Format: uri */
            publicUrl: string;
            name: string;
            /** Format: uri */
            redirectLink?: string;
            type?: string;
            /** Format: uuid */
            uploaderId: string;
        };
        ImageFullUpdateDto: {
            caption?: string;
            description?: string;
            /** Format: uri */
            publicUrl?: string;
            name?: string;
            /** Format: uri */
            redirectLink?: string;
            type?: string;
            /** Format: uuid */
            uploaderId?: string;
        };
        ImageBriefResponseDto: {
            /** Format: uuid */
            id?: string;
            caption?: string;
            /** Format: uri */
            publicUrl: string;
            /** Format: uri */
            redirectLink?: string;
            type?: string;
        };
        EventCategoryBriefResponseDto: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
        };
        EventCategoryResponseDto: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            description?: string;
        };
        EventCategoryBaseDto: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            createdAt: Record<string, never>;
            updatedAt: Record<string, never>;
        };
        HistoricalEventBaseDto: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            thumbnailId?: string;
            fromDay?: number | null;
            fromMonth?: number | null;
            fromYear: number;
            toDay?: number | null;
            toMonth?: number | null;
            toYear?: number | null;
            content: string;
            /** Format: uuid */
            authorId: string;
            createdAt: Record<string, never>;
            updatedAt: Record<string, never>;
        };
        HistoricalEventBaseCreateDto: {
            /** Format: uuid */
            authorId: string;
            name: string;
            /** Format: uuid */
            thumbnailId?: string;
            fromDay?: number | null;
            fromMonth?: number | null;
            fromYear: number;
            toDay?: number | null;
            toMonth?: number | null;
            toYear?: number | null;
            content: string;
        };
        HistoricalEventBaseUpdateDto: {
            name?: string;
            /** Format: uuid */
            thumbnailId?: string;
            fromDay?: number | null;
            fromMonth?: number | null;
            fromYear?: number;
            toDay?: number | null;
            toMonth?: number | null;
            toYear?: number | null;
            content?: string;
            /** Format: uuid */
            authorId?: string;
        };
        HistoricalEventQueryDto: {
            page?: number;
            limit?: number;
            search?: string;
            sortBy?: string;
            /** @enum {string} */
            sortOrder?: "asc" | "desc";
            /** Format: uuid */
            authorId?: string;
            categoryIds?: string[];
            fromYear?: number;
            fromMonth?: number;
            fromDay?: number;
            toYear?: number;
            toMonth?: number;
            toDay?: number;
            searchYear?: number;
            /** Format: date-time */
            createdAtFrom?: string;
            /** Format: date-time */
            createdAtTo?: string;
            /** Format: date-time */
            updatedAtFrom?: string;
            /** Format: date-time */
            updatedAtTo?: string;
        };
        HistoricalEventBulkDeleteDto: {
            eventIds: string[];
        };
        HistoricalEventBriefResponseDto: {
            thumbnail?: components["schemas"]["ImageBriefResponseDto"] | null;
            /** Format: uuid */
            id: string;
            name: string;
            fromDay?: number | null;
            fromMonth?: number | null;
            fromYear: number;
            toDay?: number | null;
            toMonth?: number | null;
            toYear?: number | null;
        };
        EventCategoriesBaseDto: {
            eventId: string;
            categoryId: string;
        };
        HistoricalEventPreviewResponseDto: {
            thumbnail?: components["schemas"]["ImageBriefResponseDto"] | null;
            /** Format: uuid */
            id: string;
            name: string;
            fromDay?: number | null;
            fromMonth?: number | null;
            fromYear: number;
            toDay?: number | null;
            toMonth?: number | null;
            toYear?: number | null;
            author: components["schemas"]["UserBaseResponseDto"];
            categories: components["schemas"]["EventCategoriesBaseDto"][];
        };
        HistoricalEventDetailResponseDto: {
            thumbnail?: components["schemas"]["ImageBriefResponseDto"] | null;
            /** Format: uuid */
            id: string;
            name: string;
            fromDay?: number | null;
            fromMonth?: number | null;
            fromYear: number;
            toDay?: number | null;
            toMonth?: number | null;
            toYear?: number | null;
            author: components["schemas"]["UserBaseResponseDto"];
            categories: components["schemas"]["EventCategoriesBaseDto"][];
            content: string;
        };
        RoleBaseUpdateDto: {
            name?: string;
            slug?: string;
            description?: string;
            status?: Record<string, never>;
            grants?: components["schemas"]["GrantBaseCreateDto"][];
        };
        GrantBaseDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            roleId: string;
            /** Format: uuid */
            resourceId: string;
            action: string;
            attribute?: string;
        };
        GrantBaseUpdateDto: {
            /** Format: uuid */
            roleId?: string;
            /** Format: uuid */
            resourceId?: string;
            action?: string;
            attribute?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_signUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_signIn: {
        parameters: {
            query?: never;
            header: {
                "x-refresh-token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_verifyEmailToken: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoleController_getRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>[];
                };
            };
        };
    };
    RoleController_createRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleBaseCreateDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoleController_getRoleById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    RoleController_deleteRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoleController_addGrants: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    RoleController_deleteRoleGrant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: string;
                resourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ResourceController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResourceController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateResourceDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResourceController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResourceController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
