/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/historical-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HistoricalEventController_getAllHistoricalEvents"];
        put?: never;
        post: operations["HistoricalEventController_createHistoricalEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/historical-events/{id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HistoricalEventController_getHistoricalEventPreviewById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/historical-events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HistoricalEventController_getHistoricalEventById"];
        put: operations["HistoricalEventController_updateHistoricalEvent"];
        post?: never;
        delete: operations["HistoricalEventController_deleteHistoricalEvent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UserController_createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["UserController_deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HistoricalEventBaseCreateDto: {
            /** Format: uuid */
            authorId: string;
            name: string;
            /** Format: uuid */
            thumbnailId?: string;
            fromDay?: number | null;
            fromMonth?: number | null;
            fromYear: number;
            toDay?: number | null;
            toMonth?: number | null;
            toYear?: number | null;
            content: string;
        };
        ImageBriefResponseDto: {
            /** Format: uuid */
            id?: string;
            caption?: string;
            /** Format: uri */
            publicUrl: string;
            /** Format: uri */
            redirectLink?: string;
            type?: string;
        };
        HistoricalEventBriefResponseDto: {
            thumbnail?: components["schemas"]["ImageBriefResponseDto"] | null;
            /** Format: uuid */
            id: string;
            name: string;
            fromDay?: number | null;
            fromMonth?: number | null;
            fromYear: number;
            toDay?: number | null;
            toMonth?: number | null;
            toYear?: number | null;
        };
        UserBaseResponseDto: {
            /** Format: uuid */
            id: string;
            firstName: string;
            lastName?: string | null;
            slug: string;
        };
        EventCategoriesBaseDto: {
            eventId: string;
            categoryId: string;
        };
        HistoricalEventDetailResponseDto: {
            thumbnail?: components["schemas"]["ImageBriefResponseDto"] | null;
            /** Format: uuid */
            id: string;
            name: string;
            fromDay?: number | null;
            fromMonth?: number | null;
            fromYear: number;
            toDay?: number | null;
            toMonth?: number | null;
            toYear?: number | null;
            content: string;
            author: components["schemas"]["UserBaseResponseDto"];
            categories: components["schemas"]["EventCategoriesBaseDto"][];
        };
        HistoricalEventBaseUpdateDto: {
            name?: string;
            /** Format: uuid */
            thumbnailId?: string;
            fromDay?: number | null;
            fromMonth?: number | null;
            fromYear?: number;
            toDay?: number | null;
            toMonth?: number | null;
            toYear?: number | null;
            content?: string;
            /** Format: uuid */
            authorId?: string;
        };
        UserBaseDto: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            slug: string;
            firstName: string;
            lastName?: string | null;
            /** Format: uuid */
            avatarId?: string;
            status: Record<string, never>;
        };
        UserDeleteDto: {
            /** Format: uuid */
            userId: string;
        };
        UserBulkDeleteDto: {
            userIds: string[];
        };
        UserQueryDto: {
            page?: number;
            limit?: number;
            search?: string;
            sortBy?: string;
            /** @enum {string} */
            sortOrder?: "asc" | "desc";
            status?: string;
            sex?: string;
            /** Format: date-time */
            birthdateFrom?: string;
            /** Format: date-time */
            birthdateTo?: string;
            /** Format: date-time */
            createdAtFrom?: string;
            /** Format: date-time */
            createdAtTo?: string;
        };
        UserFullDto: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            slug: string;
            firstName: string;
            lastName?: string | null;
            /** Format: uuid */
            avatarId?: string;
            status: Record<string, never>;
            address?: string;
            /** Format: date-time */
            birthdate?: string;
            msisdn?: string;
            sex?: Record<string, never>;
            createdAt: Record<string, never>;
            updatedAt: Record<string, never>;
        };
        UserFullCreateDto: {
            slug?: string;
            /** Format: email */
            email: string;
            firstName: string;
            lastName?: string | null;
            /** Format: uuid */
            avatarId?: string;
            status: Record<string, never>;
            address?: string;
            /** Format: date-time */
            birthdate?: string;
            msisdn?: string;
            sex?: Record<string, never>;
        };
        UserFullUpdateDto: {
            /** Format: email */
            email?: string;
            firstName?: string;
            lastName?: string | null;
            /** Format: uuid */
            avatarId?: string;
            status?: Record<string, never>;
            address?: string;
            /** Format: date-time */
            birthdate?: string;
            msisdn?: string;
            sex?: Record<string, never>;
            slug?: string;
        };
        UserFullResponseDto: {
            avatar: string | null;
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            slug: string;
            firstName: string;
            lastName?: string | null;
            address?: string;
            /** Format: date-time */
            birthdate?: string;
            msisdn?: string;
        };
        UserAuthDto: {
            password: string;
            salt: string;
            username: string;
            /** Format: uuid */
            roleId: string;
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            status: Record<string, never>;
        };
        UserAuthCreateDto: {
            /** Format: email */
            email: string;
            status: Record<string, never>;
            password: string;
            salt: string;
            username: string;
            /** Format: uuid */
            roleId: string;
        };
        UserAuthUpdateDto: {
            /** Format: email */
            email?: string;
            status?: Record<string, never>;
            password?: string;
            salt?: string;
            username?: string;
            /** Format: uuid */
            roleId?: string;
        };
        RoleBaseDto: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            status: Record<string, never>;
            description: string;
        };
        UserAuthWithRoleDto: {
            password: string;
            salt: string;
            username: string;
            /** Format: uuid */
            roleId: string;
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            status: Record<string, never>;
            role: components["schemas"]["RoleBaseDto"];
        };
        RoleBriefResponseDto: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
        };
        UserPayloadDto: {
            role: components["schemas"]["RoleBriefResponseDto"];
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
        };
        TokenPairDto: {
            accessToken: string;
            refreshToken: string;
        };
        RefreshTokenResponseDto: {
            user: components["schemas"]["UserPayloadDto"];
            tokens: components["schemas"]["TokenPairDto"];
        };
        SignInDto: {
            username: string;
            password: string;
            browserId: string;
        };
        SignUpDto: {
            /** Format: email */
            email: string;
        };
        JwtPermissionDto: {
            role: string;
            resource: string;
            action: string;
            attribute: string;
        };
        JwtPayloadDto: {
            /**
             * Format: uuid
             * @description Id người dùng
             */
            userId: string;
            /**
             * Format: email
             * @description Email người dùng
             */
            email: string;
            /** @description Fingerprint trình duyệt */
            browserId: string;
            /** @description Permissions của người dùng */
            permissions: components["schemas"]["JwtPermissionDto"][];
        };
        QueryImageDto: {
            page?: number;
            limit?: number;
            search?: string;
            sortBy?: string;
            /** @enum {string} */
            sortOrder?: "asc" | "desc";
            name?: string;
            type?: string;
            /** Format: uuid */
            uploaderId?: string;
            /** Format: date-time */
            createdAtFrom?: string;
            /** Format: date-time */
            createdAtTo?: string;
            /** Format: date-time */
            updatedAtFrom?: string;
            /** Format: date-time */
            updatedAtTo?: string;
        };
        BulkDeleteImageDto: {
            imageIds: string[];
        };
        ImageBaseDto: {
            /** Format: uuid */
            id?: string;
            caption?: string;
            description?: string;
            /** Format: uri */
            publicUrl: string;
        };
        ImageFullDto: {
            /** Format: uuid */
            id?: string;
            caption?: string;
            description?: string;
            /** Format: uri */
            publicUrl: string;
            name: string;
            /** Format: uri */
            redirectLink?: string;
            type?: string;
            /** Format: uuid */
            uploaderId: string;
        };
        ImageFullCreateDto: {
            caption?: string;
            description?: string;
            /** Format: uri */
            publicUrl: string;
            name: string;
            /** Format: uri */
            redirectLink?: string;
            type?: string;
            /** Format: uuid */
            uploaderId: string;
        };
        ImageFullUpdateDto: {
            caption?: string;
            description?: string;
            /** Format: uri */
            publicUrl?: string;
            name?: string;
            /** Format: uri */
            redirectLink?: string;
            type?: string;
            /** Format: uuid */
            uploaderId?: string;
        };
        EventCategoryBriefResponseDto: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
        };
        EventCategoryResponseDto: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            description?: string;
        };
        EventCategoryBaseDto: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            createdAt: Record<string, never>;
            updatedAt: Record<string, never>;
        };
        HistoricalEventBaseDto: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            thumbnailId?: string;
            fromDay?: number | null;
            fromMonth?: number | null;
            fromYear: number;
            toDay?: number | null;
            toMonth?: number | null;
            toYear?: number | null;
            content: string;
            /** Format: uuid */
            authorId: string;
            createdAt: Record<string, never>;
            updatedAt: Record<string, never>;
        };
        HistoricalEventQueryDto: {
            page?: number;
            limit?: number;
            search?: string;
            sortBy?: string;
            /** @enum {string} */
            sortOrder?: "asc" | "desc";
            /** Format: uuid */
            authorId?: string;
            categoryIds?: string[];
            fromYear?: number;
            fromMonth?: number;
            fromDay?: number;
            toYear?: number;
            toMonth?: number;
            toDay?: number;
            searchYear?: number;
            /** Format: date-time */
            createdAtFrom?: string;
            /** Format: date-time */
            createdAtTo?: string;
            /** Format: date-time */
            updatedAtFrom?: string;
            /** Format: date-time */
            updatedAtTo?: string;
        };
        HistoricalEventBulkDeleteDto: {
            eventIds: string[];
        };
        HistoricalEventPreviewResponseDto: {
            thumbnail?: components["schemas"]["ImageBriefResponseDto"] | null;
            /** Format: uuid */
            id: string;
            name: string;
            fromDay?: number | null;
            fromMonth?: number | null;
            fromYear: number;
            toDay?: number | null;
            toMonth?: number | null;
            toYear?: number | null;
            author: components["schemas"]["UserBaseResponseDto"];
            categories: components["schemas"]["EventCategoriesBaseDto"][];
        };
        GrantBaseCreateDto: {
            /** Format: uuid */
            roleId: string;
            /** Format: uuid */
            resourceId: string;
            action: string;
            attribute?: string;
        };
        RoleBaseCreateDto: {
            status: Record<string, never>;
            grants?: components["schemas"]["GrantBaseCreateDto"][];
            name: string;
            slug: string;
            description: string;
        };
        RoleBaseUpdateDto: {
            name?: string;
            slug?: string;
            description?: string;
            status?: Record<string, never>;
            grants?: components["schemas"]["GrantBaseCreateDto"][];
        };
        GrantBaseDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            roleId: string;
            /** Format: uuid */
            resourceId: string;
            action: string;
            attribute?: string;
        };
        GrantBaseUpdateDto: {
            /** Format: uuid */
            roleId?: string;
            /** Format: uuid */
            resourceId?: string;
            action?: string;
            attribute?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HistoricalEventController_getAllHistoricalEvents: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                search?: string;
                sortBy?: string;
                sortOrder?: "asc" | "desc";
                authorId?: string;
                categoryIds?: string[];
                fromYear?: number;
                fromMonth?: number;
                fromDay?: number;
                toYear?: number;
                toMonth?: number;
                toDay?: number;
                searchYear?: number;
                createdAtFrom?: string;
                createdAtTo?: string;
                updatedAtFrom?: string;
                updatedAtTo?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HistoricalEventController_createHistoricalEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HistoricalEventBaseCreateDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoricalEventBriefResponseDto"];
                };
            };
        };
    };
    HistoricalEventController_getHistoricalEventPreviewById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoricalEventDetailResponseDto"];
                };
            };
        };
    };
    HistoricalEventController_getHistoricalEventById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoricalEventDetailResponseDto"];
                };
            };
        };
    };
    HistoricalEventController_updateHistoricalEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HistoricalEventBaseUpdateDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    HistoricalEventController_deleteHistoricalEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserBaseDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
