/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/historical-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HistoricalEventController_getAllHistoricalEvents"];
        put?: never;
        post: operations["HistoricalEventController_createHistoricalEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/historical-events/{id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HistoricalEventController_getHistoricalEventPreviewById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/historical-events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HistoricalEventController_getHistoricalEventById"];
        put: operations["HistoricalEventController_updateHistoricalEvent"];
        post?: never;
        delete: operations["HistoricalEventController_deleteHistoricalEvent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UserController_createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["UserController_deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HistoricalEventBaseCreateDto: {
            /** Format: uuid */
            authorId: string;
            name: string;
            /** Format: uuid */
            thumbnailId?: string;
            fromDay?: number | null;
            fromMonth?: number | null;
            fromYear: number;
            toDay?: number | null;
            toMonth?: number | null;
            toYear?: number | null;
            content: string;
        };
        ImageBriefResponseDto: {
            /** Format: uuid */
            id?: string;
            caption?: string;
            /** Format: uri */
            publicUrl: string;
            /** Format: uri */
            redirectLink?: string;
            type?: string;
        };
        HistoricalEventBriefResponseDto: {
            thumbnail?: components["schemas"]["ImageBriefResponseDto"] | null;
            /** Format: uuid */
            id: string;
            name: string;
            fromDay?: number | null;
            fromMonth?: number | null;
            fromYear: number;
            toDay?: number | null;
            toMonth?: number | null;
            toYear?: number | null;
        };
        UserBaseResponseDto: {
            /** Format: uuid */
            id: string;
            firstName: string;
            lastName?: string | null;
            slug: string;
        };
        EventCategoriesBaseDto: {
            eventId: string;
            categoryId: string;
        };
        HistoricalEventDetailResponseDto: {
            thumbnail?: components["schemas"]["ImageBriefResponseDto"] | null;
            /** Format: uuid */
            id: string;
            name: string;
            fromDay?: number | null;
            fromMonth?: number | null;
            fromYear: number;
            toDay?: number | null;
            toMonth?: number | null;
            toYear?: number | null;
            content: string;
            author: components["schemas"]["UserBaseResponseDto"];
            categories: components["schemas"]["EventCategoriesBaseDto"][];
        };
        HistoricalEventBaseUpdateDto: {
            name?: string;
            /** Format: uuid */
            thumbnailId?: string;
            fromDay?: number | null;
            fromMonth?: number | null;
            fromYear?: number;
            toDay?: number | null;
            toMonth?: number | null;
            toYear?: number | null;
            content?: string;
            /** Format: uuid */
            authorId?: string;
        };
        UserBaseDto: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            slug: string;
            firstName: string;
            lastName?: string | null;
            /** Format: uuid */
            avatarId?: string;
            status: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HistoricalEventController_getAllHistoricalEvents: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                search?: string;
                sortBy?: string;
                sortOrder?: "asc" | "desc";
                authorId?: string;
                categoryIds?: string[];
                fromYear?: number;
                fromMonth?: number;
                fromDay?: number;
                toYear?: number;
                toMonth?: number;
                toDay?: number;
                searchYear?: number;
                createdAtFrom?: string;
                createdAtTo?: string;
                updatedAtFrom?: string;
                updatedAtTo?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HistoricalEventController_createHistoricalEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HistoricalEventBaseCreateDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoricalEventBriefResponseDto"];
                };
            };
        };
    };
    HistoricalEventController_getHistoricalEventPreviewById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoricalEventDetailResponseDto"];
                };
            };
        };
    };
    HistoricalEventController_getHistoricalEventById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoricalEventDetailResponseDto"];
                };
            };
        };
    };
    HistoricalEventController_updateHistoricalEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HistoricalEventBaseUpdateDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    HistoricalEventController_deleteHistoricalEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserBaseDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
